# Generated by Django 4.0.4 on 2022-05-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermodel',
            name='doc_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
