# Generated by Django 4.0.4 on 2022-05-12 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(choices=[('SE', 'Sedan Model'), ('CO', 'Convertible Model'), ('HA', 'Hatch Model')], max_length=2)),
                ('color', models.CharField(choices=[('Y', 'Yellow Color'), ('B', 'Blue Color'), ('G', 'Grey Color')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.ownermodel')),
            ],
        ),
    ]
